[package]
name = "cli"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "whale"

[dependencies]
chrono = "0.4.26"
whale = { path = "../whale" }
nu-ansi-term = "0.47"
rayon = "1.7.0"
reedline = "0.20.0"
clap = { version = "4.3.17", features = ["derive"] }
